name: CD - Deploy AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd ${{ secrets.DEPLOY_PATH }}
          
          # Fazer pull do código
          git pull origin main
          
          # Parar containers antigos
          docker-compose down || true
          
          # Fazer build e iniciar novos containers
          docker-compose up --build -d
          
          # Aguardar aplicação iniciar
          sleep 10
          
          # Verificar health check
          if curl -f http://localhost:5000/health; then
            echo "Health check passed!"
          else
            echo "Health check failed!"
            exit 1
          fi

    