name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t bisb-api:latest .

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name bisb-api bisb-api:latest
      
      - name: Healthcheck
        run: |
          echo "Waiting for application to start..."
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.DEPLOY_SERVER }}:5000/health || true)
            if [ "$STATUS" == "200" ]; then
              echo "Application is healthy!"
              exit 0
            fi
            echo "Attempt $i: not ready yet (status: $STATUS)"
            sleep 5
          done
          echo "Healthcheck failed after 10 attempts."
          exit 1